micronaut:
  application:
    name: library-back-end
  server:
    port: 8080
  packages: com.example

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: library_user
    password: library_pw
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
